project:
  type: website
  output-dir: docs

website:
  title: "Your website name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Project Highlights
        menu:
          - text: Statistics
            href: data_visualizations.qmd
          - text: Data Science/Other
            href: other_highlights.qmd
    right:
      - icon: envelope
        href: "mailto:jacobposner22@gmail.com"
      - text: Linkedin
        icon: linkedin
        href: "www.linkedin.com/in/jacob-posner-092635264"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



